In [1]:
import numpy as np


In [15]:
zero = np.array(5)
one = np.array([1, 2, 3], [4, 5, 7], [2, 3, 4])
n = np.array([[1, 2], [3, 4], [5, 6]])
reshaped = n.reshape(2, 3)
a = np.arange(1,5)
print(np.arange(0.5, 10.4, 0.8))
conca = np.concatenate((n, one))
print(conca)
print(reshaped, a)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [10]:
# Get both the array and the step size
arr, step = np.linspace(0, 10, num=5, retstep=True)
print("Array:", arr)
print("Step size:", step)


Array: [ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


In [13]:
print(np.empty((2,2)))
print(np.eye(4))


[[ 2.5  5. ]
 [ 7.5 10. ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
