In [9]:
# problem 1: Array Creation
import numpy as np

empty_array = np.empty ((2, 2)) #1
ones_array = np.ones((4, 2)) #2

filled_array = np.full((3, 3), 5) #3
arr = np.array([[4, 6], [8, 10]]) #4, 5
zeros_like_array = np.zeros_like(arr) #4
ones_like_array = np.ones_like(arr) #5
new_list = [4, 6, 8, 10] #6
numpy_array = np.array(new_list) #6


print(
    "1. Empty Array (2x2):", empty_array,
    "2. Ones Array (4x2):", ones_array,
    "3. Filled Array (3x3 with 5):", filled_array,
    "4. Zeros Array (same shape as reference_array):", zeros_like_array,
    "5. Ones Array (same shape as reference_array):", ones_like_array,
    "6. NumPy Array converted from new_list:", numpy_array,
    sep='\n'
)


1. Empty Array (2x2):
[[-2.    1.  ]
 [ 1.75 -0.75]]
2. Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3. Filled Array (3x3 with 5):
[[5 5 5]
 [5 5 5]
 [5 5 5]]
4. Zeros Array (same shape as reference_array):
[[0 0]
 [0 0]]
5. Ones Array (same shape as reference_array):
[[1 1]
 [1 1]]
6. NumPy Array converted from new_list:
[ 4  6  8 10]


In [10]:
# Problem 2: Array Manipulation: Numerical Ranges and Array Indexing

# 1. Array with values ranging from 10 to 49
arr1 = np.arange(10, 50)

# 2. 3x3 Matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)

# 3. 3x3 Identity Matrix
identity_matrix = np.eye(3)

# 4. Random array of size 30 and its mean
arr3 = np.random.random(30)
mean_value = arr3.mean()

# 5. 10x10 random array and min/max values
arr4 = np.random.random((10, 10))
min_value = arr4.min()
max_value = arr4.max()

# 6. Zero array of size 10, replacing 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1

# 7. Reversed array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

# 8. Border array with 1s on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0

# 9. Checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(
    "1. Array with values ranging from 10 to 49:", arr1,
    "2. 3x3 Matrix with values from 0 to 8:", arr2,
    "3. 3x3 Identity Matrix:", identity_matrix,
    "4. Random array of size 30 and its mean:", arr3, "Mean:", mean_value,
    "5. 10x10 random array, Min and Max values:", arr4, "Min:", min_value, "Max:", max_value,
    "6. Zero array with 5th element replaced by 1:", zero_array,
    "7. Reversed array:", reversed_arr,
    "8. Border array with 1s on the border and 0 inside:", border_array,
    "9. Checkerboard pattern:", checkerboard,
    sep='\n'
)


1. Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. Random array of size 30 and its mean:
[0.01331897 0.82435625 0.32559686 0.30096176 0.67444647 0.06503706
 0.23073883 0.45857856 0.81202137 0.12722498 0.17324366 0.4878131
 0.89895628 0.69961117 0.55669893 0.14105381 0.82667041 0.84110339
 0.12697395 0.38567935 0.94792552 0.91021694 0.18360706 0.00529168
 0.73779081 0.69446773 0.45037444 0.03586755 0.35555091 0.45922784]
Mean:
0.45834685456081087
5. 10x10 random array, Min and Max values:
[[0.95882447 0.8674545  0.68952193 0.36820457 0.61327504 0.14252016
  0.10807378 0.08576466 0.72059492 0.919685  ]
 [0.86493792 0.11644997 0.57609227 0.39284553 0.24004416 0.65199914
  0.02799459 0.41416345 0.9870852  0.63155567]
 [0.58063105 0.3570715  0.9672

In [11]:
# Problem 3: Array Operations

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
arr1 = x + y

# 2. Subtract the two arrays
arr2 = x - y

# 3. Multiply the array with any integer 
arr3 = x * 5

# 4. Square each element of the array
arr4 = np.square(x)

# 5. Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)  
dot_xy = np.dot(x, y)

# 6. Concatenate x and y along rows; Concatenate v and w along columns
concatenate_xy = np.concatenate((x, y), axis=0)  # Along rows
concatenate_vw = np.column_stack((v, w))  # Along columns

# 7. Concatenate x and v
try:
    concatenate_xv = np.concatenate((x, v), axis=0)  
except ValueError as e:
    concatenate_xv_error = str(e)


print(
    "1. Sum of x and y:\n", arr1,
    "\n\n2. Difference of x and y:\n", arr2,
    "\n\n3. x scaled by 5:\n", arr3,
    "\n\n4. Square of each element in x:\n", arr4,
    "\n\n5. Dot products:\n",
    "v and w:", dot_vw,
    "\nx and v:\n", dot_xv,
    "\nx and y:\n", dot_xy,
    "\n\n6. Concatenation along rows (x and y):\n", concatenate_xy,
    "\nConcatenation along columns (v and w):\n", concatenate_vw,
    "\n\n7. Attempt to concatenate x and v:\n", concatenate_xv_error,
    sep='\n'
)


1. Sum of x and y:

[[ 6  8]
 [10 13]]


2. Difference of x and y:

[[-4 -4]
 [-4 -3]]


3. x scaled by 5:

[[ 5 10]
 [15 25]]


4. Square of each element in x:

[[ 1  4]
 [ 9 25]]


5. Dot products:

v and w:
219

x and v:

[29 77]

x and y:

[[19 22]
 [50 58]]


6. Concatenation along rows (x and y):

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation along columns (v and w):

[[ 9 11]
 [10 12]]


7. Attempt to concatenate x and v:

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [12]:
#Problem 4: Matrix Operations
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inverse = np.linalg.inv(A)  # Find the inverse of A
identity_matrix = np.dot(A, A_inverse)  # A * A^-1
identity_matrix = np.round(identity_matrix, decimals=10) 

# 2. Prove AB ≠ BA
AB = np.dot(A, B)  # Matrix multiplication AB
BA = np.dot(B, A)  # Matrix multiplication BA

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)  # (AB)^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T

print(
    "1. A.A^(-1) = I:\n", identity_matrix,
    "\n\n2. AB:\n", AB,
    "\nBA:\n", BA,
    "\nAB ≠ BA: ", not np.array_equal(AB, BA),
    "\n\n3. (AB)^T:\n", AB_transpose,
    "\nB^T * A^T:\n", BT_AT,
    "\n(AB)^T = B^T * A^T: ", np.array_equal(AB_transpose, BT_AT),
    sep="\n"
)

# Coefficient matrix (A) and result vector (B)
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B = np.array([-1, -3, 9])

# Using the inverse method
A_inverse = np.linalg.inv(A)  # Find inverse of A
X = np.dot(A_inverse, B)  # Solution vector X = A^(-1) * B

print(
    "\n\nSolving the system of equations:",
    "\nSolution vector X:\n", X,
    sep="\n"
)



1. A.A^(-1) = I:

[[1. 0.]
 [0. 1.]]


2. AB:

[[23 13]
 [51 29]]

BA:

[[36 44]
 [13 16]]

AB ≠ BA: 
True


3. (AB)^T:

[[23 51]
 [13 29]]

B^T * A^T:

[[23 51]
 [13 29]]

(AB)^T = B^T * A^T: 
True


Solving the system of equations:

Solution vector X:

[ 2.  1. -2.]


# About Linalg
**a module in NumPy- short for "Linear Algebra"-includes a collection of methods. For problem 4, linalg.inv is used to find the inverse of the matrix.**


# How fast is NumPy? An Experiment


In [13]:
#1. Element-wise Addition
import time

# Python Lists
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start = time.time()

result_list_add = []
for i in range(len(list1)):
    result_list_add.append(list1[i] + list2[i])

end = time.time()
print(f"Time taken for element-wise addition using Python lists: {end - start:.5f}s")


# NumPy Arrays
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start = time.time()
result_numpy_add = array1 + array2
end = time.time()
print(f"Time taken for element-wise addition using NumPy arrays: {end - start:.5f}s")


Time taken for element-wise addition using Python lists: 0.37454s
Time taken for element-wise addition using NumPy arrays: 0.00675s


for element-wise addition, numpy is faster.

In [14]:
#2. Element-wise Multiplication
import time

# Python Lists
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start = time.time()

result_list_mult = []
for i in range(len(list1)):
    result_list_mult.append(list1[i] * list2[i])

end = time.time()
print(f"Time taken for element-wise multiplication using Python lists: {end - start:.5f}s")

# NumPy Arrays
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start = time.time()
result_numpy_mult = array1 * array2
end = time.time()
print(f"Time taken for element-wise multiplication using NumPy arrays: {end - start:.5f}s")


Time taken for element-wise multiplication using Python lists: 0.45249s
Time taken for element-wise multiplication using NumPy arrays: 0.00317s


numpy is faster.

In [15]:
#3. Dot Product
import time

# Python Lists
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start = time.time()

result_list_dot = 0
for i in range(len(list1)):
    result_list_dot += list1[i] * list2[i]

end = time.time()
print(f"Time taken for dot product using Python lists: {end - start:.5f}s")

#Numpy Arrays
array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start = time.time()
result_numpy_dot = np.dot(array1, array2)
end = time.time()
print(f"Time taken for dot product using NumPy arrays: {end - start:.5f}s")


Time taken for dot product using Python lists: 0.31453s
Time taken for dot product using NumPy arrays: 0.01109s


In [18]:
#4. Matrix Multiplication
import time

# Python Lists
matrix1 = [[j for j in range(1000)] for i in range(1000)]
matrix2 = [[j for j in range(1000)] for i in range(1000)]

start = time.time()

result_list_matmult = [[
    sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix1[0])))
    for j in range(len(matrix2[0]))
] for i in range(len(matrix1))]

end = time.time()
print(f"Time taken for matrix multiplication using Python lists: {end - start:.5f}s")

# NumPy Arrays
matrix1_np = np.arange(1000000).reshape(1000, 1000)
matrix2_np = np.arange(1000000).reshape(1000, 1000)

start = time.time()
result_numpy_matmult = np.dot(matrix1_np, matrix2_np)
end = time.time()
print(f"Time taken for matrix multiplication using NumPy arrays: {end - start:.5f}s")


Time taken for matrix multiplication using Python lists: 232.46551s
Time taken for matrix multiplication using NumPy arrays: 2.22657s


## From the last four cells, it has been recorded that NumPy surely is way faster than Python lists. First, I will try to list down why NumPy had the lead here. 

1. **NumPy is implemented in compiled languages that are C and Fortran.** Python, on the other hand, is an interpreted language, so NumPy is significantly faster than Python. 
2. **Python lists perform operations element by element.** In most of my code, for operations, I have implemented a loop for every element, which is inherently slower in Python. However, NumPy uses vectorized operations, i.e., it processes an entire array in one go.

---

## Could NumPy have been slower than Python lists?

**Yes, when there are small data sets to work with.**

To put it briefly, while working with computationally heavy tasks like matrix multiplication, addition, subtraction, and more, **NumPy was faster in our case due to vectorization, optimized algorithms, and low-level memory efficiency.**